Algoritmo "Maioridade"
// Disciplina  : [Algoritmo I]
// Descrição   : Algoritmo para ler a idade de uma pessoa, determinar e mostrar se a pessoa é maior ou menor de idade
// Autor(a)    : Diego Alves Dias
// Data atual  : 14/04/2022
Var
idade:inteiro

Inicio
escreva("Digite sua idade: ")
leia(idade)
  se idade >= 18 entao
    escreva("Maior de idade")
  senao
    escreva("Menor de idade")
  fimse
Fimalgoritmo